name: C++/Python CI
on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: pip install pytest pybind11
        
      - name: Configure and Build C++
        run: |
          mkdir build && cd build
          cmake /Users/divyadsouza/anaconda3/lib/python3.11/site-packages/pybind11/share/cmake/pybind11
          make
          
      - name: Run Pytest with Profiling
        run: pytest -s  # -s allows you to see the runtime print statements
